### ISSUE TITLE
Publish Version 2.6.1

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#2667]
### Description
Version 2.6.0 has an obvious bug, local image resource cant display correct. see #2664 #2652 #2644.
The bug is already fixed in this [commit](https://github.com/facebook/fresco/commit/3a4aad2fbb9f546b40beebf2f8b0d9d2a8955351), Please publish a new version.

**Comment by s1rius** [comment]
@oprisnik Please have a look :)

**Comment by mateosilguerolemon** [comment]
Hi ! Is there an update about this ?

**Comment by tiago-yoneda** [comment]
@oprisnik @defHLT any way we can get an update on this?

**Comment by nodzhang** [comment]
Hi,2.6.1 Is it not released?

**Comment by mikehardy** [comment]
Is this library available as an on demand build from jitpack? Because this image cache error bit me and seeing it is fixed even, but not released, is unexpected

**Comment by mikehardy** [comment]
I asked on the general react-native discord since it has some audience among facebook folks. Commit history looks *busy* so maybe just a coordination thing, or it's planned

**Comment by pierroo** [comment]
Hi @mikehardy you are literally everywhere it's crazy :)
Did you get more news on this issue?

I got hit by this unexpected bug while pushing an update in production, it is quite a mess right now and I need to push a fixed update as soon as possible.

I wonder how did this happen in the first place?
I never faced this cache issue before, and I didn't even update react-native for months yet I did push some app update that went okay without cache issue.

Can fresco gets updated sneakily independently from react native from time to time upon building for release?

**Comment by mikehardy** [comment]
It is *possible* for fresco to get updated sneakily, you may look at your android dependencies with the gradle `dependencies` task (for react-native where the "app" is in the "app" submodule it is `./gradlew :app:dependencies > dependencies.txt` then I look through the text file)

In react-native this dependency won't slip unless you specifically bump the dependency on purpose to test it like I do (which behavior - testing new versions - is why you see me everywhere - I find the problems before most do, and actually try to fix them ;-) )

You can use gradle to pin the dependency though, that's what I do, and then when 2.6.1 (or whatever future version is released with the fix) I can move the dep. Until then I pin the dep with these lines in my gradle file - you can put similar things in there

```
mike@bistromath:~/work/Kullki/ksocialscore/packages/public-app/android (p2p-features) % cat build.gradle app/build.gradle |grep -i fresco
        frescoVersion = '2.5.0' // Pinned to 2.5.0 until https://github.com/facebook/fresco/issues/2667 https://github.com/facebook/fresco/releases
    implementation("com.facebook.fresco:animated-gif:${rootProject.ext.frescoVersion}")
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {

```

**Comment by pierroo** [comment]
Thank you @mikehardy 

I wish I understood half the things you explained there. :)
I really don't come from an android development environment, so playing with those gradle files isn't my specialty.

I talked about this issue here as well https://github.com/facebook/react-native/issues/32671

It was mentioned I should add the following before my dependencies:

configurations.all {
resolutionStrategy {
force "com.facebook.fresco:fresco:2.5.0"
}
}

But then when I do gradlew :app:dependencies I still see a lot of fresco that remains under 2.6.0:
![image](https://user-images.githubusercontent.com/17619412/197343029-a2c91ef4-2a57-4491-b6a5-c6169f081640.png)

Do I have to force the same configuration for all lines mentioning fresco on 2.6.0?

Or is this what your lines do in your gradle file?

why is fresco:animated-gif specifically mentioned here, when I thought it was a com.facebook.fresco:2.6.0 issue? (like the "root" fresco)?

**Comment by mikehardy** [comment]
That resolution strategy looks correct, however your dependencies graph does show some sort of issue. Why? I don't know - I apologize but I won't have time to help you troubleshoot your project. You are on the right path with dependency-inspection + resolution pinning though

**Comment by pierroo** [comment]
Almost one year old and yet this thread remains valid: not sure who we should reach out for on this particular matter?
Of course rolling back to 2.5.0 fixes the issue, but then I'm afraid EVENTUALLY this old version will no longer work with new versions of react native etc.

A 2.6.1 would be very welcome :)

**Comment by quantiantechnologies** [comment]
when this will get fixed?

**Comment by quantiantechnologies** [comment]
it is not fixed yet. please Reopen the issue.

**Comment by cortinico** [comment]
> it is not fixed yet. please Reopen the issue.

Version 3.0.0 got published which contains the fix you requested.

**Comment by tiago-yoneda** [comment]
Can anyone confirm that the issue is resolved in the 3.0.0 version?

**Comment by quantiantechnologies** [comment]
yes please tell

**Comment by efstathiosntonas** [comment]
It fixed it for me but now I've started seeing this bug on `react-native@0.71.10` on Android 12 and 13 (so far):

```stacktrace

java.lang.IncompatibleClassChangeError: Found interface com.facebook.imagepipeline.image.CloseableImage, but class was expected (declaration of 'com.facebook.imagepipeline.image.CloseableImage' appears in base.apk)
        at com.facebook.react.modules.image.ImageLoaderModule$1.onNewResultImpl(ImageLoaderModule.java:125)
        at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:51)
        at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:200)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:46)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:208)
        at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:182)
        at com.facebook.datasource.AbstractDataSource.setResult(AbstractDataSource.java:242)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onNewResultImpl(AbstractProducerToDataSourceAdapter.kt:59)
        at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:69)
        at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:26)
        at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$createConsumer$1.onNewResultImpl(AbstractProducerToDataSourceAdapter.kt:39)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:183)
        at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:134)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleResult(DecodeProducer.kt:373)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.kt:244)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder._init_$lambda$2(DecodeProducer.kt:412)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.$r8$lambda$KZ-YIhcmQg_RJ489kdh-N9D6sow(Unknown)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$$ExternalSyntheticLambda0.run(Unknown:6)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:231)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:28)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
        at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4(Unknown)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$$ExternalSyntheticLambda0.run(Unknown:4)
        at java.lang.Thread.run(Thread.java:1012)

```

**Comment by pioner92** [comment]
> Thank you @mikehardy
> 
> I wish I understood half the things you explained there. :) I really don't come from an android development environment, so playing with those gradle files isn't my specialty.
> 
> I talked about this issue here as well [facebook/react-native#32671](https://github.com/facebook/react-native/issues/32671)
> 
> It was mentioned I should add the following before my dependencies:
> 
> ```
> configurations.all {
> resolutionStrategy {
> force "com.facebook.fresco:fresco:2.5.0"
> }
> }
> ```
> 
> But then when I do gradlew :app:dependencies I still see a lot of fresco that remains under 2.6.0: ![image](https://user-images.githubusercontent.com/17619412/197343029-a2c91ef4-2a57-4491-b6a5-c6169f081640.png)
> 
> Do I have to force the same configuration for all lines mentioning fresco on 2.6.0?
> 
> Or is this what your lines do in your gradle file?
> 
> why is fresco:animated-gif specifically mentioned here, when I thought it was a com.facebook.fresco:2.6.0 issue? (like the "root" fresco)?

I fixed it 

```
dependencies {

    configurations.all {
        resolutionStrategy {
            force "com.facebook.fresco:fresco:2.5.0"
            force "com.facebook.fresco:fbcore:2.5.0"
            force "com.facebook.fresco:imagepipeline:2.5.0"
            force "com.facebook.fresco:imagepipeline-base:2.5.0"
            force "com.facebook.fresco:imagepipeline-native:2.5.0"
            force "com.facebook.fresco:memory-type-ashmem:2.5.0"
            force "com.facebook.fresco:memory-type-native:2.5.0"
            force "com.facebook.fresco:memory-type-java:2.5.0"
        }
    }
```

**Comment by quantiantechnologies** [comment]
> > Thank you @mikehardy
> > I wish I understood half the things you explained there. :) I really don't come from an android development environment, so playing with those gradle files isn't my specialty.
> > I talked about this issue here as well [facebook/react-native#32671](https://github.com/facebook/react-native/issues/32671)
> > It was mentioned I should add the following before my dependencies:
> > ```
> > configurations.all {
> > resolutionStrategy {
> > force "com.facebook.fresco:fresco:2.5.0"
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But then when I do gradlew :app:dependencies I still see a lot of fresco that remains under 2.6.0: ![image](https://user-images.githubusercontent.com/17619412/197343029-a2c91ef4-2a57-4491-b6a5-c6169f081640.png)
> > Do I have to force the same configuration for all lines mentioning fresco on 2.6.0?
> > Or is this what your lines do in your gradle file?
> > why is fresco:animated-gif specifically mentioned here, when I thought it was a com.facebook.fresco:2.6.0 issue? (like the "root" fresco)?
> 
> I fixed it
> 
> ```
> dependencies {
> 
>     configurations.all {
>         resolutionStrategy {
>             force "com.facebook.fresco:fresco:2.5.0"
>             force "com.facebook.fresco:fbcore:2.5.0"
>             force "com.facebook.fresco:imagepipeline:2.5.0"
>             force "com.facebook.fresco:imagepipeline-base:2.5.0"
>             force "com.facebook.fresco:imagepipeline-native:2.5.0"
>             force "com.facebook.fresco:memory-type-ashmem:2.5.0"
>             force "com.facebook.fresco:memory-type-native:2.5.0"
>             force "com.facebook.fresco:memory-type-java:2.5.0"
>         }
>     }
> ```



> > Thank you @mikehardy
> > I wish I understood half the things you explained there. :) I really don't come from an android development environment, so playing with those gradle files isn't my specialty.
> > I talked about this issue here as well [facebook/react-native#32671](https://github.com/facebook/react-native/issues/32671)
> > It was mentioned I should add the following before my dependencies:
> > ```
> > configurations.all {
> > resolutionStrategy {
> > force "com.facebook.fresco:fresco:2.5.0"
> > }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But then when I do gradlew :app:dependencies I still see a lot of fresco that remains under 2.6.0: ![image](https://user-images.githubusercontent.com/17619412/197343029-a2c91ef4-2a57-4491-b6a5-c6169f081640.png)
> > Do I have to force the same configuration for all lines mentioning fresco on 2.6.0?
> > Or is this what your lines do in your gradle file?
> > why is fresco:animated-gif specifically mentioned here, when I thought it was a com.facebook.fresco:2.6.0 issue? (like the "root" fresco)?
> 
> I fixed it
> 
> ```
> dependencies {
> 
>     configurations.all {
>         resolutionStrategy {
>             force "com.facebook.fresco:fresco:2.5.0"
>             force "com.facebook.fresco:fbcore:2.5.0"
>             force "com.facebook.fresco:imagepipeline:2.5.0"
>             force "com.facebook.fresco:imagepipeline-base:2.5.0"
>             force "com.facebook.fresco:imagepipeline-native:2.5.0"
>             force "com.facebook.fresco:memory-type-ashmem:2.5.0"
>             force "com.facebook.fresco:memory-type-native:2.5.0"
>             force "com.facebook.fresco:memory-type-java:2.5.0"
>         }
>     }
> ```
I will try this for next version and share the review.

**Comment by efstathiosntonas** [comment]
> It fixed it for me but now I've started seeing this bug on `react-native@0.71.10` on Android 12 and 13 (so far):
> 
> ```
> 
> java.lang.IncompatibleClassChangeError: Found interface com.facebook.imagepipeline.image.CloseableImage, but class was expected (declaration of 'com.facebook.imagepipeline.image.CloseableImage' appears in base.apk)
>         at com.facebook.react.modules.image.ImageLoaderModule$1.onNewResultImpl(ImageLoaderModule.java:125)
>         at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:51)
>         at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:200)
>         at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:46)
>         at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:208)
>         at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:182)
>         at com.facebook.datasource.AbstractDataSource.setResult(AbstractDataSource.java:242)
>         at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.onNewResultImpl(AbstractProducerToDataSourceAdapter.kt:59)
>         at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:69)
>         at com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter.onNewResultImpl(CloseableProducerToDataSourceAdapter.java:26)
>         at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter$createConsumer$1.onNewResultImpl(AbstractProducerToDataSourceAdapter.kt:39)
>         at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
>         at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
>         at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
>         at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
>         at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
>         at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:183)
>         at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer$1.onNewResultImpl(BitmapMemoryCacheProducer.java:134)
>         at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.handleResult(DecodeProducer.kt:373)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.kt:244)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder._init_$lambda$2(DecodeProducer.kt:412)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.$r8$lambda$KZ-YIhcmQg_RJ489kdh-N9D6sow(Unknown)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$$ExternalSyntheticLambda0.run(Unknown:6)
>         at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:231)
>         at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:28)
>         at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:97)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
>         at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
>         at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4(Unknown)
>         at com.facebook.imagepipeline.core.PriorityThreadFactory$$ExternalSyntheticLambda0.run(Unknown:4)
>         at java.lang.Thread.run(Thread.java:1012)
> ```

I’ve updated to 3.1.0 today on react-native@0.72.6 and I still get this error. 🥹

**Comment by pierroo** [comment]
Kinda weird, I never faced the above error (java.lang.IncompatibleClassChangeError: etc), but now that I upgraded from RN 0.69.12 to latest 0.73.4 every screen that have an <Image /> will crash with this error log.

@efstathiosntonas did you fix it since?
another question, how do you actually "update" fresco to 3.1.0?

simply with the same as above?


   ```
 configurations.all {
        resolutionStrategy {
            force "com.facebook.fresco:fresco:2.5.0"
            force "com.facebook.fresco:fbcore:2.5.0"
            force "com.facebook.fresco:imagepipeline:2.5.0"
            force "com.facebook.fresco:imagepipeline-base:2.5.0"
            force "com.facebook.fresco:imagepipeline-native:2.5.0"
            force "com.facebook.fresco:memory-type-ashmem:2.5.0"
            force "com.facebook.fresco:memory-type-native:2.5.0"
            force "com.facebook.fresco:memory-type-java:2.5.0"
        }
    }
```

**Comment by Ajololr** [comment]
In my case, `java.lang.IncompatibleClassChangeError` `Caused by: java.lang.IncompatibleClassChangeError: class com.facebook.imagepipeline.image.CloseableAnimatedImage has interface com.facebook.imagepipeline.image.CloseableImage as super class` was fixed by updating the version of com.facebook.fresco:* gif dependencies to the respective version of react native (2.5.0 -> 3.1.3) https://reactnative.dev/docs/image#gif-and-webp-support-on-android
