### ISSUE TITLE
cannot load image with Proguard

### ISSUE THREAD

**Issue by lizhiqiang-unnoo** [facebook/fresco#447]
Android 5.1.0

After enable proguard, nether BaseControllerListener.onFinalImageSet nor BaseControllerListener.onFailure is called.
After disable proguard, it works fine, onFinalImageSet is called.
Both 0.5.2 and 0.5.3 act the same.

I have added [proguard_fresco.pro](http://frescolib.org/docs/proguard.html) as suggested.

Here is my build.gradle:

```
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

buildscript {
    repositories {
        jcenter()

    }

    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.unnoo.xiaomiquan"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 100
        versionName "3.0.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            versionNameSuffix " (debug)"

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
        }

        release {
            versionNameSuffix " (alph1)"

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
        }
    }

    try {
        signingConfigs {
            .....
        }
    } catch (e) {
        throw new InvalidUserDataException("You should define KEYSTORE_PASSWORD and KEY_PASSWORD in gradle.properties: " + e)
    }

    packagingOptions {
        exclude 'LICENSE'
        exclude 'LICENSE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'LICENSE'
        exclude 'LICENSE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    //
    // 测试库
    //
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.0-rc3'
    androidTestCompile 'com.android.support.test:runner:0.3'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-contrib:2.2'
    // 可以改成androidTestCompile ?
    debugCompile 'org.mockito:mockito-core:2.0.13-beta'
    debugCompile 'org.hamcrest:hamcrest-core:1.3' 
    //
    // 官方库
    //
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:support-v13:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.android.support:palette-v7:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:support-annotations:22.2.0'
    compile 'com.android.support:gridlayout-v7:22.2.0'
    //
    // 第三方库
    //
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'de.greenrobot:greendao:1.3.7'
    compile 'de.greenrobot:java-common:2.0.0'
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.3'
    compile 'org.projectlombok:lombok:1.16.4'
    compile 'com.facebook.fresco:fresco:0.5.2'
    compile 'com.mcxiaoke.volley:library:1.0.15'
    compile 'com.koushikdutta.async:androidasync:2.1.4'
    compile 'com.yqritc:recyclerview-flexibledivider:1.2.5'
    // dagger
    provided 'org.glassfish:javax.annotation:10.0-b28'
    compile 'com.google.dagger:dagger:2.0.1'
    apt 'com.google.dagger:dagger-compiler:2.0.1'
}

```

my proguard-rules.pro

```
-dontwarn **

#
# 还原时显示代码行数，参考：http://stackoverflow.com/a/6670172
#
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable

#
# 微信
#
-keep class com.tencent.mm.sdk.modelmsg.WXMediaMessage { *;}
-keep class com.tencent.mm.sdk.modelmsg.** implements com.tencent.mm.sdk.modelmsg.WXMediaMessage$IMediaObject {*;}

#
#
#
-keep class com.tencent.mtt.external.** { *; }

#
# volley
#
-keep class com.android.volley.** { *; }

#
# 信鸽推送
#
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep class com.tencent.android.tpush.**  {* ;}

#
# EventBus
#
-keepclassmembers class ** {
    public void onEvent*(**);
}

#
# GreenDao
#
-keepclassmembers class * extends de.greenrobot.dao.AbstractDao {
    public static java.lang.String TABLENAME;
}
-keep class **$Properties

#
# design support library
#
-keep class android.support.design.widget.** { *; }
-keep interface android.support.design.widget.** { *; }

```

Thanks!

**Comment by lizhiqiang-unnoo** [comment]
This problem may have relation to SharedElementTransition. 
I have two activity: 
- MainActivity, contains a RecyclerView with a list of SimpleDraweeView showing thumbnails.
- PhotoViewerActivity, contains a SimpleDraweeView for thumbnail and a ZoomableDraweeView for full size image.

With proguard disabled, press SimpleDraweeView in MainActivity, PhotoViewActivity launched with a SharedElementTransition, showing a SimpleDrawwView for thumbnail and a progressbar over it. After full size image loaded, both thumbnail view and progress are hide, and the full size image is showing in ZoomableDraweeView.

After enable proguard, the SharedElementTransition does not work.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.

**Comment by anooshkhalid** [comment]
I still face this same issue with ZoomableDraweeView not loading the image
