### ISSUE TITLE
android studio library project dependencies fresco 0.9.0 fail!

### ISSUE THREAD

**Issue by my519820363** [facebook/fresco#955]
android studio(2.0, android plug v1.5) main project dependencies fresco 0.9.0, normal running.
but android studio(2.0, android plug v1.5) library project dependencies fresco 0.9.0, compile pass. but main project not found about fresco class.

android studio(2.0, android plug v1.5) 主工程直接引入fresco0.9.0，正常运行.
但是android studio(2.0, android plug v1.5)库工程引入fresco0.9.0，编译正常. 但是在主工程中却找不到fresco的类

**Comment by my519820363** [comment]
0.8.1 normal

**Comment by plamenko** [comment]
I don't understand the issue. Is your app throwing an exception in the runtime? If so, can you provide the stack trace?

**Comment by my519820363** [comment]
My project has two module: app and library

when i configured fresco:0.9.0 in module app ,it works precisely.。

but when it configured in module  library，the app can not  get fresco。

in other words，i hope library contains fresco，And app contains library

Curiously  fresco 0.8.1 can be used normally in both cases.

**Comment by my519820363** [comment]
android {
    compileSdkVersion cfg.compileVersion
    buildToolsVersion cfg.buildToolsVersion

    defaultConfig {
        minSdkVersion cfg.minSdk
        targetSdkVersion cfg.targetSdk
        versionCode cfg.version_code
        versionName cfg.version_name
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "LOG_DEBUG", "true"
            minifyEnabled false 
        }

        release {
            buildConfigField "boolean", "LOG_DEBUG", "false"
            minifyEnabled false
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile "com.facebook.fresco:fresco:0.9.0"
}

**Comment by massimocarli** [comment]
@my519820363 Could you please provide us the error log? I tried to create a project with Android Studio 2.0beta7, Android plugin 1.5 putting fresco dependency into the gradle file for the library and everything is fine. If you provide us the error log we can try to reproduce it.
Thanks

**Comment by ICECHN** [comment]
![1](https://cloud.githubusercontent.com/assets/11832023/13136446/8851fb2c-d654-11e5-8c23-3bec3d2ee024.jpg)
![2](https://cloud.githubusercontent.com/assets/11832023/13136447/88592604-d654-11e5-8cbf-d1a8224eed2e.jpg)

**Comment by ICECHN** [comment]
Resolved! DiskCacheConfig.newBuilder() ==> DiskCacheConfig.newBuilder(context)

**Comment by my519820363** [comment]
![bc525744-1b72-4afa-8f66-e33f7c4455ed](https://cloud.githubusercontent.com/assets/1789647/13137106/ba14123a-d659-11e5-9af0-998b08a28d96.png)

my issue still unresolved!

**Comment by my519820363** [comment]
![02b41bd4-8b71-4f2b-a5f0-d95371353975](https://cloud.githubusercontent.com/assets/1789647/13137216/6d4bde14-d65a-11e5-9ad9-05499e9a1999.png)

my issuse still unresolved!

**Comment by my519820363** [comment]
![48ae721b-3722-416d-914e-539da6a46dc7](https://cloud.githubusercontent.com/assets/1789647/13137374/8ee95762-d65b-11e5-97cd-79982a44a5d1.png)

and 0.8.1 could build sucess

**Comment by ICECHN** [comment]
@my519820363 
Resolved! DiskCacheConfig.newBuilder() ==> DiskCacheConfig.newBuilder(context)

**Comment by my519820363** [comment]
@ICECHN  Resolved! Tks!
